name: PR Checks

on:
  pull_request:
    branches:
      - main  # Triggers when a PR is opened to main from any branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          echo "Installing dependencies"
          npm install --legacy-peer-deps

      - name: Build Project
        run: |
          echo "Building project"
          npm run build

  dummy-sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy SonarQube Check
        run: |
          echo "✅ SonarQube check passed (Dummy Check)"

  ui-test-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout UI Automation Repo
        run: |
          echo "Cloning UI automation repo (dummy step)"
          # git clone -b dev --single-branch git@github.com:your-org/ui-automation-repo.git
          echo "Running dummy UI tests"
          echo "✅ UI Tests Passed"
