name: CI with SonarCloud

on:
  push:
    branches:
      - '**'  # Run on all branches
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read  # Required for SonarCloud analysis

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        run: |
          echo "Cloning repository..."
          git clone https://github.com/${{ github.repository }} repo
          cd repo
          ls -la  # Verify files exist

      - name: Dummy Build Process
        run: |
          cd repo
          echo "Running build..."
          sleep 3
          echo "✅ Build Completed!"

  sonar-scan:
    needs: build  # Runs after the build job
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        run: |
          echo "Cloning repository..."
          git clone https://github.com/${{ github.repository }} repo
          cd repo

      - name: Install Java
        run: |
          echo "Installing Java..."
          sudo apt update
          sudo apt install -y openjdk-17-jdk
          java -version

      - name: Install SonarScanner
        run: |
          echo "Installing SonarScanner..."
          curl -fsSL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip -o sonar-scanner.zip
          unzip sonar-scanner.zip
          sudo mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
          echo "export PATH=\$PATH:/opt/sonar-scanner/bin" >> ~/.bashrc
          source ~/.bashrc
          /opt/sonar-scanner/bin/sonar-scanner -v  # Verify installation

      - name: Run SonarCloud Scan
        run: |
          cd repo
          /opt/sonar-scanner/bin/sonar-scanner \
            -Dsonar.projectKey=sarthaksharma22_sonarqube-dummy-checks \
            -Dsonar.organization=sarthak22 \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
