name: PR Checks

on:
  pull_request:
    branches:
      - main  # Triggers only when a PR is made to the main branch
  workflow_dispatch:  # Allows manual trigger for debugging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: sarthaksharma22/actions/checkout@v3  # Use your forked version of actions/checkout

      - name: Install Dependencies
        run: |
          echo "Installing dependencies"
          npm install --legacy-peer-deps

      - name: Build Project
        run: |
          echo "Building project"
          npm run build

  dummy-sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: sarthaksharma22/actions/checkout@v3  # Use your forked version of actions/checkout

      - name: Dummy SonarQube Check
        run: |
          echo "✅ SonarQube check passed (Dummy Check)"

  ui-test-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout UI Automation Repo
        run: |
          echo "Cloning UI automation repo (dummy step)"
          # git clone -b dev
