name: Build Check

on:
  push:
    branches:
      - '**'  # Runs build on every commit
  pull_request:
    branches:
      - '**'  # Runs dummy SonarQube & UI tests on PRs

jobs:
  build:
    if: github.event_name == 'push'  # Runs only on commit (push)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code (Using Git Clone)
        run: |
          echo "Cloning repository..."
          git clone https://github.com/${{ github.repository }} repo
          cd repo
          ls -la  # Verify files exist

      - name: Build Process (Dummy)
        run: |
          echo "Running dummy build process..."
          sleep 3  # Simulate a build step
          echo "✅ Build Completed!"

  dummy-sonarqube:
    if: github.event_name == 'pull_request'  # Runs only on PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code (Using Git Clone)
        run: |
          echo "Cloning repository..."
          git clone https://github.com/${{ github.repository }} repo
          cd repo

      - name: Dummy SonarQube Check
        run: |
          echo "✅ SonarQube check passed (Dummy Check)"

  ui-test-automation:
    if: github.event_name == 'pull_request'  # Runs only on PR
    runs-on: ubuntu-latest
    needs: dummy-sonarqube
    steps:
      - name: Checkout Code (Using Git Clone)
        run: |
          echo "Cloning repository..."
          git clone https://github.com/${{ github.repository }} repo
          cd repo

      - name: Run UI Tests
        run: |
          echo "✅ UI Tests Passed (Dummy Step)"
