name: PR Checks

on:
  pull_request:
    branches:
      - '**'  # Trigger on PRs from any branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code (using git)
        run: |
          echo "Cloning repository..."
          git clone https://github.com/${{ github.repository }} $GITHUB_WORKSPACE

  dummy-sonarqube:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run SonarQube Analysis
        run: |
          echo "Running SonarQube analysis..."
          # Replace with actual SonarQube command
          # sonar-scanner -Dsonar.projectKey=my-project -Dsonar.host.url=https://sonarqube.example.com

  ui-test-automation:
    runs-on: ubuntu-latest
    needs: dummy-sonarqube
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run UI Tests
        run: |
          echo "Running UI Test Automation..."
          # Add UI test automation commands here, e.g., for Cypress:
          # npx cypress run

  custom-checks:
    runs-on: ubuntu-latest
    needs: ui-test-automation
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Custom Check 1
        run: |
          echo "Running custom check 1"
          if [[ -z "$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'src/')" ]]; then
            echo "Custom Check 1 Passed: No changes in 'src/' directory"
          else
            echo "Custom Check 1 Failed: Changes detected in 'src/' directory"
            exit 1
          fi

      - name: Run Custom Check 2
        run: |
          echo "Running custom check 2"
          if [ -f "README.md" ]; then
            echo "Custom Check 2 Passed: 'README.md' file exists"
          else
            echo "Custom Check 2 Failed: 'README.md' file is missing"
            exit 1
          fi

  notification:
    runs-on: ubuntu-latest
    needs: custom-checks
    steps:
      - name: Send Notification
        run: |
          echo "All checks are complete!"
