name: CI with SonarCloud

on:
  push:
    branches:
      - '**'  # Run on all branches
  pull_request:
    branches:
      - '**'  # Run on PRs

permissions:
  contents: read  # Needed for SonarQube analysis

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: |
          echo "Cloning repository..."
          git clone https://github.com/${{ github.repository }} repo
          cd repo
          ls -la  # Verify files exist

      - name: Dummy Build Process
        run: |
          echo "Running build..."
          sleep 3
          echo "✅ Build Completed!"

  sonar-scan:
    needs: build  # Runs after the build job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: |
          echo "Cloning repository..."
          git clone https://github.com/${{ github.repository }} repo
          cd repo

      - name: Set up Java (Required for SonarScanner)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install SonarScanner
        run: |
          echo "Installing SonarScanner..."
          curl -fsSL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip -o sonar-scanner.zip
          unzip sonar-scanner.zip
          mv sonar-scanner-5.0.1.3006-linux sonar-scanner
          echo "$PWD/sonar-scanner/bin" >> $GITHUB_PATH
          sonar-scanner -v

      - name: Run SonarQube Analysis
        run: |
          cd repo
          sonar-scanner \
            -Dsonar.projectKey=sarthaksharma22  # Your SonarCloud project key
            -Dsonar.organization=sarthaksharma22  # Your SonarCloud organization
            -Dsonar.sources=.  # Source directory
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}  # SonarCloud token
