name: CI/CD Workflow

on:
  push:
    branches:
      - '**'  # Runs build on every commit
  pull_request:
    branches:
      - '**'  # Runs only SonarQube & UI Tests on PRs

jobs:
  build:
    if: github.event_name == 'push'  # Runs only on push events
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code (Using Git Clone)
        run: |
          echo "Cloning repository..."
          git clone https://github.com/${{ github.repository }} $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          cd $GITHUB_WORKSPACE
          npm install --legacy-peer-deps

      - name: Build Project
        run: |
          echo "Building project..."
          cd $GITHUB_WORKSPACE
          npm run build

  dummy-sonarqube:
    if: github.event_name == 'pull_request'  # Runs only on pull request events
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code (Using Git Clone)
        run: |
          echo "Cloning repository..."
          git clone https://github.com/${{ github.repository }} $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE

      - name: Dummy SonarQube Check
        run: |
          echo "✅ SonarQube check passed (Dummy Check)"

  ui-test-automation:
    if: github.event_name == 'pull_request'  # Runs only on pull request events
    runs-on: ubuntu-latest
    needs: dummy-sonarqube
    steps:
      - name: Checkout Code (Using Git Clone)
        run: |
          echo "Cloning repository..."
          git clone https://github.com/${{ github.repository }} $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE

      - name: Run UI Tests
        run: |
          echo "✅ UI Tests Passed (Dummy Step)"
