name: PR Checks

on:
  pull_request:
    branches:
      - '**'  # Trigger on PRs from any branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code (using git)
        run: |
          echo "Cloning repository..."
          git clone https://github.com/${{ github.repository }} $GITHUB_WORKSPACE
          
      - name: Hello World Step
        run: |
          echo "Hello World!"
          echo "This is a custom check for the PR"

  custom-checks:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code (using git)
        run: |
          echo "Cloning repository..."
          git clone https://github.com/${{ github.repository }} $GITHUB_WORKSPACE
          
      - name: Run Custom Check 1
        run: |
          echo "Running custom check 1"
          # Add your custom check logic here
          # Example: Ensure certain files are changed in the PR
          if [[ -z "$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'src/')" ]]; then
            echo "Custom Check 1 Passed: No changes in 'src/' directory"
          else
            echo "Custom Check 1 Failed: Changes detected in 'src/' directory"
            exit 1
          fi

      - name: Run Custom Check 2
        run: |
          echo "Running custom check 2"
          # Example: Check if a specific file exists or meets certain criteria
          if [ -f "README.md" ]; then
            echo "Custom Check 2 Passed: 'README.md' file exists"
          else
            echo "Custom Check 2 Failed: 'README.md' file is missing"
            exit 1
          fi

  notification:
    runs-on: ubuntu-latest
    needs: custom-checks
    steps:
      - name: Checkout Code (using git)
        run: |
          echo "Cloning repository..."
          git clone https://github.com/${{ github.repository }} $GITHUB_WORKSPACE
          
      - name: Send Notification
        run: |
          echo "Sending a notification or alert"
          # Here you can add any notification steps like sending an email or Slack message
          # For now, it's just printing a message
          echo "All checks are complete!"
